config/routes.rb
Rails4app::Application.routes.draw do
  resources :boys

  

end

app/models/boy.rb
class Boy < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boys_controller.rb
class BoysController < ApplicationController
  before_action :set_boy, only: [:show, :edit, :update, :destroy]

  # GET /boys
  # GET /boys.json
  def index
    @boys = Boy.all
  end

  # GET /boys/1
  # GET /boys/1.json
  def show
  end

  # GET /boys/new
  def new
    @boy = Boy.new
  end

  # GET /boys/1/edit
  def edit
  end

  # POST /boys
  # POST /boys.json
  def create
    @boy = Boy.new(boy_params)

    respond_to do |format|
      if @boy.save
        format.html { redirect_to @boy, notice: 'Boy was successfully created.' }
        format.json { render action: 'show', status: :created, location: @boy }
      else
        format.html { render action: 'new' }
        format.json { render json: @boy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boys/1
  # PATCH/PUT /boys/1.json
  def update
    respond_to do |format|
      if @boy.update(boy_params)
        format.html { redirect_to @boy, notice: 'Boy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @boy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boys/1
  # DELETE /boys/1.json
  def destroy
    @boy.destroy
    respond_to do |format|
      format.html { redirect_to boys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boy
      @boy = Boy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boy_params
      params.require(:boy).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boys_helper.rb
module BoysHelper
end

app/views/boys/_form.html.erb
<%= form_for(@boy) do |f| %>
  <% if @boy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boy.errors.count, "error") %> prohibited this boy from being saved:</h2>

      <ul>
      <% @boy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boys/edit.html.erb
<h1>Editing boy</h1>

<%= render 'form' %>

<%= link_to 'Show', @boy %> |
<%= link_to 'Back', boys_path %>

app/views/boys/index.html.erb
<h1>Listing boys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @boys.each do |boy| %>
      <tr>
        <td><%= boy.name %></td>
        <td><%= link_to 'Show', boy %></td>
        <td><%= link_to 'Edit', edit_boy_path(boy) %></td>
        <td><%= link_to 'Destroy', boy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boy', new_boy_path %>

app/views/boys/new.html.erb
<h1>New boy</h1>

<%= render 'form' %>

<%= link_to 'Back', boys_path %>

app/views/boys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @boy.name %>
</p>

<%= link_to 'Edit', edit_boy_path(@boy) %> |
<%= link_to 'Back', boys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4app</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>